---
- name: Run nginx via Docker
  hosts: webserver
  remote_user: ubuntu
  become: yes
  tasks:

    - name: Install docker and python dependencies
      apt:
        name:
          - python3-pip
          - python3-docker
          - docker.io
        update_cache: yes

    - name: Start docker service
      service:
        name: docker
        state: started

    - name: Install docker python module
      pip:
        name: docker

    - name: Make build directory
      file:
        path: "build/"
        state: directory
        mode: 0755

    - name: Move files to build directory
      copy:
        src: "files/"
        dest: "build/"
        mode: 0644

    - name: Build Docker image
      command: docker build -t "nginx" "build/"

    - name: Run Docker container
      docker_container:
        name: "nginx-container"
        image: "nginx"
        state: started
        recreate: yes
        published_ports:
          - "80:80"
