name: Check ansible playbook with ansible Lint 

on: [push, pull_request]

jobs:
  Check_ansible_playbook_with_ansible_lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint Ansible Playbook
      uses: ansible/ansible-lint-action@master
      with:
        targets: "./ansible/prod/*.yml"
        args: "-q"
